# Generated by Django 5.2.17 on 2026-09-14 05:52

import uploads.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('original_name', models.CharField(max_length=255)),
                ('original', models.FileField(upload_to=uploads.models.original_path)),
                ('file_type', models.CharField(max_length=4)),
                ('size', models.PositiveIntegerField()),
                ('encoding', models.CharField(blank=True, max_length=16)),
                ('analysis', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
