# Generated by Django 5.2.17 on 2026-09-15 07:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.TextField()),
                ('provider', models.CharField(default='anthropic', max_length=40)),
                ('model', models.CharField(db_index=True, max_length=100)),
                ('request_body', models.JSONField()),
                ('approval_note', models.TextField()),
                ('approved_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('started', 'Started'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('unknown', 'Unknown')], default='started', max_length=16)),
                ('response_body', models.TextField(blank=True)),
                ('parsed_result', models.JSONField(blank=True, null=True)),
                ('validation_error', models.TextField(blank=True)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('provider_request_id', models.CharField(blank=True, max_length=255)),
                ('usage', models.JSONField(default=dict)),
                ('error_type', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveBigIntegerField(blank=True, null=True)),
                ('upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_calls', to='uploads.upload')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
